id: AC4DB1517
base_file: f8751.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:10:55.653469
  last_modified_at: 2022-06-05 20:10:55.653472
