id: AC4DB1517
base_file: fE5BA.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:10:55.674142
  last_modified_at: 2022-06-05 20:10:55.674145
