id: AC4DB1517
base_file: f476E.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:10:55.643170
  last_modified_at: 2022-06-05 20:10:55.643175
