id: AC4DB1517
base_file: f8EC7.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:10:55.662302
  last_modified_at: 2022-06-05 20:10:55.662320
