id: AC4DB1517
base_file: fC6AA.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:10:55.668692
  last_modified_at: 2022-06-05 20:10:55.668695
