id: AC4DB1517
base_file: fC8F8.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:10:55.669844
  last_modified_at: 2022-06-05 20:10:55.669847
