id: AC4DB1517
base_file: fCCFD.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:10:55.670920
  last_modified_at: 2022-06-05 20:10:55.670923
