id: AC4DB1517
base_file: f3EE8.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:10:55.641185
  last_modified_at: 2022-06-05 20:10:55.641193
